// Mongoose models generated by BuildX
const mongoose = require('mongoose');
const { Schema } = mongoose;

const usersSchema = new Schema({
  email: { type: String },
  password: { type: String },
  googleOauthId: { type: String }
}, { timestamps: true });
const Users = mongoose.model('Users', usersSchema);

const jobPostingsSchema = new Schema({
  title: { type: String },
  description: { type: String },
  userId: { type: String }
}, { timestamps: true });
const JobPostings = mongoose.model('JobPostings', jobPostingsSchema);

const bidsSchema = new Schema({
  jobPostingId: { type: String },
  userId: { type: String },
  amount: { type: String }
}, { timestamps: true });
const Bids = mongoose.model('Bids', bidsSchema);

const contractsSchema = new Schema({
  jobPostingId: { type: String },
  userId: { type: String },
  bidId: { type: String },
  status: { type: String }
}, { timestamps: true });
const Contracts = mongoose.model('Contracts', contractsSchema);

const paymentsSchema = new Schema({
  contractId: { type: String },
  amount: { type: String },
  status: { type: String }
}, { timestamps: true });
const Payments = mongoose.model('Payments', paymentsSchema);

const ratingsSchema = new Schema({
  contractId: { type: String },
  userId: { type: String },
  rating: { type: String },
  review: { type: String }
}, { timestamps: true });
const Ratings = mongoose.model('Ratings', ratingsSchema);

module.exports = { Users, JobPostings, Bids, Contracts, Payments, Ratings };
